development: &development
  adapter: mysql2
  encoding: utf8
  database: bball_development
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost

test:
  <<: *development
  database: bball_test

production:
  <<: *development
  database: bball_production
