development: &development
  adapter: postgresql
  encoding: utf8
  database: bball_development
  host: localhost

test:
  <<: *development
  database: bball_test

production:
  <<: *development
  database: bball_production
